### ISSUE TITLE
The iOS bundle is too big

### ISSUE THREAD

**Issue by kcdev001** [irondash/cargokit#73]
Thank you for creating this project that has greatly aided my development efforts.

I'm get an issue where the compiled iOS package, the output framework lib size is too large. 

```
 keychat_rust_ffi_plugin.framework                                    24 MB
```

I integrated flutter_rust_bridge 2.1.0. 

My project:   [https://github.com/keychat-io/keychat_rust_ffi_plugin/blob/dev/ios/keychat_rust_ffi_plugin.podspec](https://github.com/keychat-io/keychat_rust_ffi_plugin/blob/dev/ios/keychat_rust_ffi_plugin.podspec)

Do you know what the reasons are? Or give analysis suggestions

**Comment by shanelau** [comment]
Same problem

**Comment by knopp** [comment]
Is that with debug or release build?

**Comment by shanelau** [comment]
> Is that with debug or release build?

release build

**Comment by nikitadol** [comment]
With this configuration, I was able to reduce the libraries for iOS:

cargokit.yaml
```yaml
cargo:
  release:
    toolchain: nightly
    extra_flags:
      - -Z
      - build-std=panic_abort,std
      - -Z
      - build-std-features=panic_immediate_abort
```

Cargo.toml
```toml
[profile.release]
debug = false
strip = true
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
rpath = true
```

```shell
RUSTFLAGS="-Crpath=yes -Zlocation-detail=none -Zfmt-debug=none"
```

The assembled library still contains paths to some files on my computer - I don't know how to solve it - @knopp, any ideas?
